name: Deploy CI/CD Pipeline

on:
    push:
        branches:
            - dev/auto-deploy

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up .env file
              run: # Create the .env file and populate it line by line
                  echo "APP_KEY=YjfB4cZWo5pCEJXhX6Hmq47WpHUodrjB" > .env
                  echo "PORT=${{ secrets.ENV_PORT }}" >> .env
                  echo "ALLOW_ORIGIN=${{ secrets.ENV_ALLOW_ORIGIN }}" >> .env
                  echo "API_V1=/api/v1" >> .env
                  echo "GIN_MODE=release" >> .env
                  echo "DB_CONNECTION=postgres" >> .env
                  echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
                  echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
                  echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
                  echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
                  echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
                  echo "DB_SSLMODE=disable" >> .env
                  echo "DB_TIMEZONE=Asia/Jakarta" >> .env
                  echo "TZ=Asia/Jakarta" >> .env
            - name: Login to Docker Hub for build
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: Build Docker Image
              run: docker build -t rfjst4real/edulink-api .
            - name: Push Docker Image to Docker Hub
              run: docker push rfjst4real/edulink-api:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Login to Docker Hub for deployment
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: Pull docker image
              run: docker pull rfjst4real/edulink-api:latest
            - name: Delete old container
              run: docker rm -f edulink-api-container
            - name: Run docker container
              run: docker run -d -p 8000:8000 --name edulink-api-container rfjst4real/edulink-api:latest
