name: Deploy CI/CD Pipeline

on:
    push:
        branches:
            - dev/auto-deploy

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub for build
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build Docker Image
              run: |
                docker build -t rfjst4real/edulink-api \
                  --build-arg APP_KEY=${{ secrets.APP_KEY }} \
                  --build-arg DB_HOST=${{ secrets.DB_HOST }} \
                  --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
                  --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                  --build-arg ENV_PORT=${{ secrets.ENV_PORT }} \
                  --build-arg ENV_ALLOW_ORIGIN=${{ secrets.ENV_ALLOW_ORIGIN }} .
            - name: Push Docker Image to Docker Hub
              run: docker push rfjst4real/edulink-api:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Login to Docker Hub for deployment
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: Pull docker image
              run: docker pull rfjst4real/edulink-api:latest
            - name: Set up .env file
              run: |
                  cat <<EOF > .env
                  APP_KEY=${{ secrets.ENV_APP_KEY }}
                  PORT=${{ secrets.ENV_PORT }}
                  ALLOW_ORIGIN=${{ secrets.ENV_ALLOW_ORIGIN }}
                  API_V1=/api/v1

                  GIN_MODE=release
                  DB_CONNECTION=postgres
                  DB_HOST=${{ secrets.DB_HOST }}
                  DB_PORT=${{ secrets.DB_PORT }}
                  DB_NAME=${{ secrets.DB_NAME }}
                  DB_USERNAME=${{ secrets.DB_USERNAME }}
                  DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                  DB_SSLMODE=disable
                  DB_TIMEZONE=Asia/Jakarta
                  TZ=Asia/Jakarta
                  EOF
            - name: Delete old container
              run: docker rm -f edulink-api-container || true
            - name: Run container with environment variables
              run: |
                docker run -d -p 8000:8000 --name edulink-api-container \
                  -e APP_KEY=${{ secrets.APP_KEY }} \
                  -e DB_HOST=${{ secrets.DB_HOST }} \
                  -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
                  -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                  -e PORT=${{ secrets.ENV_PORT }} \
                  -e ALLOW_ORIGIN=${{ secrets.ENV_ALLOW_ORIGIN }} \
                  rfjst4real/edulink-api:latest
