name: Linting CI Pipeline
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
      - name: Run golangci-lint
        run: |
          golangci-lint run
